
sudo: required
language: generic 
services: 
  - docker

before_install:
  - docker build -t shmbrg/react-test -f ./client/Dockerfile.dev ./client

script: # primary test running section
  - docker run -e CI=true shmbrg/react-test npm test

after_success:
  - docker build -t shmbrg/multi-client ./client
  - docker build -t shmbrg/multi-nginx ./nginx
  - docker build -t shmbrg/multi-server ./server
  - docker build -t shmbrg/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u shmbrg --password-stdin
  # Take those images and push them to docker hub
  - docker push shmbrg/multi-client
  - docker push shmbrg/multi-nginx
  - docker push shmbrg/multi-server
  - docker push shmbrg/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-565273500973'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY